export default [
  {
    id: 'one',
    url: 'images/popup-pic.png',
    tittle: 'Keeping track of hundreds of components',
    technologi1: 'Ruby on rails',
    technologi2: 'Css',
    technologi3: 'JavaScript',
    text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the relea',
  },
  {
    id: 'two',
    url: '/images/popup-pic.png',
    tittle: 'Keeping track of hundreds of components',
    technologi1: 'Ruby on rails',
    technologi2: 'Css',
    technologi3: 'JavaScript',
    text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the relea',
  },
  {
    id: 'three',
    url: '/images/popup-pic.png',
    tittle: 'Keeping track of hundreds of components',
    technologi1: 'Ruby on rails',
    technologi2: 'Css',
    technologi3: 'JavaScript',
    text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the relea',
  },
  {
    id: 'four',
    url: '/images/popup-pic.png',
    tittle: 'Keeping track of hundreds of components',
    technologi1: 'Ruby on rails',
    technologi2: 'Css',
    technologi3: 'JavaScript',
    text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the relea',
  },
  {
    id: 'five',
    url: '/images/popup-pic.png',
    tittle: 'Keeping track of hundreds of components',
    technologi1: 'Ruby on rails',
    technologi2: 'Css',
    technologi3: 'JavaScript',
    text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the relea',
  },
  {
    id: 'six',
    url: '/images/popup-pic.png',
    tittle: 'Keeping track of hundreds of components',
    technologi1: 'Ruby on rails',
    technologi2: 'Css',
    technologi3: 'JavaScript',
    text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the relea',
  },
];